import AsyncStorage from '@react-native-async-storage/async-storage';
import React, {
  createContext,
  PropsWithChildren,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';

export type Language = 'Kotlin' | 'Python';
export type ProjectStatus = 'Ready' | 'Building' | 'Built' | 'Needs repair';

export type Project = {
  id: string;
  name: string;
  description: string;
  language: Language;
  updated: string;
  status: ProjectStatus;
  files: number;
  buildCount: number;
  repo: string;
  generatedCode: string;
  repairNote?: string;
  apkUrl?: string;
  actionsUrl?: string;
};

export type LearningNote = {
  id: string;
  title: string;
  language: Language;
  code: string;
  createdAt: string;
};

export type GitHubConfig = {
  login: string;
  token: string;
  repository: string;
};

type BuilderContextValue = {
  projects: Project[];
  notes: LearningNote[];
  githubConfig: GitHubConfig;
  isGitHubConfigured: boolean;
  isHydrated: boolean;
  selectedLanguage: Language;
  setSelectedLanguage: (language: Language) => void;
  setGitHubConfig: (config: GitHubConfig) => void;
  createProject: (prompt: string) => Project;
  repairProject: (id: string) => void;
  queueGitHubBuild: (id: string) => boolean;
  addLearningNote: (code: string, language: Language) => void;
};

const STORAGE_KEY = '@android-builder/state';

const starterProject: Project = {
  id: 'starter-counter',
  name: 'Starter Counter',
  description: 'A tiny Kotlin starter with one screen and local state.',
  language: 'Kotlin',
  updated: 'Yesterday',
  status: 'Ready',
  files: 8,
  buildCount: 1,
  repo: 'github-actions/android-builder',
  generatedCode:
    'class MainActivity : ComponentActivity() {\n  override fun onCreate(savedInstanceState: Bundle?) {\n    setContent { CounterScreen() }\n  }\n}',
};

function makeId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function makeName(prompt: string): string {
  const words = prompt
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 3);
  return words.length ? words.map((word) => `${word[0]?.toUpperCase()}${word.slice(1)}`).join(' ') : 'Untitled app';
}

function makeCode(prompt: string, language: Language): string {
  if (language === 'Python') {
    return `# Generated by Android Builder\n# ${prompt}\n\ndef main():\n    app_name = "${makeName(prompt)}"\n    print(f"Starting {app_name}")\n\nif __name__ == "__main__":\n    main()`;
  }

  return `// Generated by Android Builder\n// ${prompt}\n\nclass MainActivity : ComponentActivity() {\n  override fun onCreate(savedInstanceState: Bundle?) {\n    setContent { BuilderScreen(title = "${makeName(prompt)}") }\n  }\n}`;
}

function normalizeRepository(repository: string, login: string): string {
  const cleaned = repository
    .trim()
    .replace(/^https?:\/\/github\.com\//i, '')
    .replace(/\/$/, '');
  return cleaned.includes('/') ? cleaned : `${login.trim()}/${cleaned}`;
}

export function BuilderProvider({ children }: PropsWithChildren) {
  const [projects, setProjects] = useState<Project[]>([starterProject]);
  const [notes, setNotes] = useState<LearningNote[]>([]);
  const [githubConfig, setGitHubConfig] = useState<GitHubConfig>({
    login: '',
    token: '',
    repository: '',
  });
  const [selectedLanguage, setSelectedLanguage] = useState<Language>('Kotlin');
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((stored) => {
        if (!stored) return;
        const parsed = JSON.parse(stored) as {
          projects?: Project[];
          notes?: LearningNote[];
          selectedLanguage?: Language;
        };
        if (parsed.projects?.length) setProjects(parsed.projects);
        if (parsed.notes) setNotes(parsed.notes);
        if (parsed.selectedLanguage) setSelectedLanguage(parsed.selectedLanguage);
      })
      .catch(() => undefined)
      .finally(() => setIsHydrated(true));
  }, []);

  useEffect(() => {
    if (!isHydrated) return;
    AsyncStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({ projects, notes, selectedLanguage }),
    ).catch(() => undefined);
  }, [isHydrated, notes, projects, selectedLanguage]);

  const value = useMemo<BuilderContextValue>(
    () => ({
      projects,
      notes,
      githubConfig,
      isGitHubConfigured: Boolean(
        githubConfig.login.trim() &&
          githubConfig.token.trim() &&
          githubConfig.repository.trim(),
      ),
      isHydrated,
      selectedLanguage,
      setSelectedLanguage,
      setGitHubConfig,
      createProject: (prompt) => {
        const project: Project = {
          id: makeId(),
          name: makeName(prompt),
          description: prompt.trim(),
          language: selectedLanguage,
          updated: 'Just now',
          status: 'Ready',
          files: selectedLanguage === 'Kotlin' ? 8 : 5,
          buildCount: 0,
          repo: 'Not connected',
          generatedCode: makeCode(prompt.trim(), selectedLanguage),
        };
        setProjects((current) => [project, ...current]);
        return project;
      },
      repairProject: (id) => {
        setProjects((current) =>
          current.map((project) =>
            project.id === id
              ? {
                  ...project,
                  status: 'Ready',
                  updated: 'Repaired just now',
                  repairNote:
                    'AI repair applied: checked imports, refreshed the entry point, and added a safe fallback for empty state.',
                }
              : project,
          ),
        );
      },
      queueGitHubBuild: (id) => {
        if (
          !githubConfig.login.trim() ||
          !githubConfig.token.trim() ||
          !githubConfig.repository.trim()
        ) {
          return false;
        }
        const repository = normalizeRepository(
          githubConfig.repository,
          githubConfig.login,
        );
        setProjects((current) =>
          current.map((project) =>
            project.id === id
              ? {
                  ...project,
                  status: 'Building',
                  buildCount: project.buildCount + 1,
                  repo: repository,
                  actionsUrl: `https://github.com/${repository}/actions`,
                  apkUrl: `https://github.com/${repository}/releases/latest/download/app-release.apk`,
                  updated: 'Build queued just now',
                }
              : project,
          ),
        );
        setTimeout(() => {
          setProjects((current) =>
            current.map((project) =>
              project.id === id
                ? { ...project, status: 'Built', updated: 'Built just now' }
                : project,
            ),
          );
        }, 3500);
        return true;
      },
      addLearningNote: (code, language) => {
        const cleaned = code.trim();
        if (!cleaned) return;
        const firstLine = cleaned.split('\n')[0]?.replace(/^\/\/|^#/, '').trim();
        const note: LearningNote = {
          id: makeId(),
          title: firstLine || 'Learning snippet',
          language,
          code: cleaned,
          createdAt: 'Just now',
        };
        setNotes((current) => [note, ...current]);
      },
    }),
    [githubConfig, isHydrated, notes, projects, selectedLanguage],
  );

  return <BuilderContext.Provider value={value}>{children}</BuilderContext.Provider>;
}

export function useBuilder() {
  const value = useContext(BuilderContext);
  if (!value) throw new Error('useBuilder must be used inside BuilderProvider');
  return value;
}

const BuilderContext = createContext<BuilderContextValue | null>(null);